In [1]:
import numpy as np

In [2]:
a = [i for i in range(1,6)]
b = sorted([i for i in range(1,6)], reverse=True)

In [6]:
a = np.array(a, int)
b = np.array(b, int)
a, b

(array([1, 2, 3, 4, 5]), array([5, 4, 3, 2, 1]))

In [7]:
test_arr = np.array(['1', '2', 3, 4], float)
test_arr

array([1., 2., 3., 4.])

In [8]:
Htype(test_arr)

numpy.ndarray

In [16]:
a = [1,2,3,4,5000]
b = [5000,4,3,2,1]

In [17]:
a is b # 리스트끼리는 메모리 주소가 당연히 다름

False

In [18]:
a[-1] is b[0] # 1의 값이 메모리 주소가 같아. 리스트는 달라도 성분별 가리키는 주소가 같아

False

In [22]:
a = np.array(a, dtype=float)
b = np.array(b, dtype=float)

In [33]:
a = np.array([[1,2,3], [2,3.9,4], [4,5,6]], dtype=np.int8)
a.nbytes

9

In [36]:
a = np.array([[1,2,3], [2,3.9,4], [4,5,6]], dtype=int)
a.dtype

dtype('int32')

In [37]:
a = np.array([[1,2,3], [2,3.9,4], [4,5,6]], dtype=float)
a.dtype

dtype('float64')

In [58]:
a = np.array([[1,2], [2,3], [4,5], [10,20]])
a.flatten()

array([ 1,  2,  2,  3,  4,  5, 10, 20])

In [71]:
a = np.array(
    [
        [1,2,3], 
        [4,5,6]
    ]
)
a[0, 0] # 0행 0열
a[1, 2] # 1행 2열
a[:, 1:] # 행 전체, 열은 1번째부터
a[1] # 1행
a[1:3]

array([[4, 5, 6]])

In [82]:
def make_zeros():
    for _ in range(10000):
        a = np.zeros(shape=(100, 100), dtype=np.int8)
        
%timeit make_zeros()

10.1 ms ± 36.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [88]:
np.empty(shape=(3, 3), dtype=int)

array([[          8,           3,           3],
       [ 1744830515,  -176595528,         404],
       [-1589381873, -2147472250,  1943742272]])

6.25 ms ± 20.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [92]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [50]:
y = y.reshape(3, 4)

In [95]:
np.eye(N=3, M=4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
np.random.normal(0, 1, 10)

array([-2.32838829,  0.09272655,  0.681922  ,  0.04816216, -1.30328154,
       -0.65644707, -0.39119381,  0.52849164, -0.29097153,  0.67880381])

In [108]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
a = np.arange(1, 7).reshape(-1, 2)
b = np.arange(3, 10).reshape(-1, 2)
a.dot()

ValueError: cannot reshape array of size 7 into shape (2)

In [127]:
a = np.arange(6).reshape(3, 2)
a * 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [136]:
a = np.array([1,3,0],)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [165]:
a = np.array([[1,4], [9,16]])
b = np.array([0,0,1,1,0])
c = np.array([0,1,1,1,1])
a[b,c]

array([ 1,  4, 16, 16,  4])

In [166]:
a[b]

array([[ 1,  4],
       [ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 1,  4]])

In [164]:
a.take(b)

array([1, 1, 4, 4, 1])

In [163]:
a.take([b,c])

array([[1, 1, 4, 4, 1],
       [1, 4, 4, 4, 4]])

In [167]:
x = np.ones((3,3))
y = np.ones((3,3))

In [171]:
X = np.array([[1, 0, 1],
         [0, 1, 0],])

In [172]:
np.linalg.pinv(X)

array([[0.5, 0. ],
       [0. , 1. ],
       [0.5, 0. ]])