In [1]:
import sys
from tqdm import tqdm
sys.path.insert(0, '../')

import torch
from torch import nn
from torch.nn import functional as F

from attention import MultiHeadAttention
from encoder import Encoder

In [2]:
D_MODEL = 6
NUM_HEADS = 2
MAX_LEN = 4
encoder = Encoder(d_model=6, num_heads=2, max_len=4)

In [13]:
rands = torch.rand(1, 4, 5)
rands

tensor([[[0.6611, 0.5318, 0.1099, 0.1732, 0.7478],
         [0.2951, 0.4061, 0.1075, 0.8161, 0.7739],
         [0.3400, 0.1615, 0.5076, 0.8063, 0.5073],
         [0.5689, 0.2168, 0.3346, 0.4579, 0.3236]]])

In [14]:
F.softmax(rands, dim=-1)

tensor([[[0.2404, 0.2113, 0.1385, 0.1476, 0.2622],
         [0.1602, 0.1789, 0.1328, 0.2696, 0.2585],
         [0.1725, 0.1443, 0.2040, 0.2751, 0.2040],
         [0.2397, 0.1686, 0.1896, 0.2145, 0.1876]]])

In [13]:
F.softmax(temp, dim=-1)

tensor([[[[0.2481, 0.2488, 0.2543, 0.2488],
          [0.2479, 0.2486, 0.2544, 0.2492],
          [0.2555, 0.2496, 0.2470, 0.2479],
          [0.2491, 0.2491, 0.2531, 0.2488]],

         [[0.2537, 0.2490, 0.2487, 0.2486],
          [0.2534, 0.2489, 0.2487, 0.2490],
          [0.2487, 0.2525, 0.2444, 0.2544],
          [0.2509, 0.2509, 0.2481, 0.2501]]],


        [[[0.2480, 0.2554, 0.2475, 0.2491],
          [0.2504, 0.2567, 0.2520, 0.2409],
          [0.2496, 0.2589, 0.2533, 0.2382],
          [0.2494, 0.2466, 0.2393, 0.2647]],

         [[0.2388, 0.2649, 0.2585, 0.2377],
          [0.2403, 0.2640, 0.2705, 0.2252],
          [0.2421, 0.2635, 0.2684, 0.2260],
          [0.2420, 0.2643, 0.2620, 0.2318]]],


        [[[0.2577, 0.2419, 0.2523, 0.2481],
          [0.2391, 0.2655, 0.2468, 0.2486],
          [0.2602, 0.2495, 0.2443, 0.2460],
          [0.2421, 0.2585, 0.2507, 0.2487]],

         [[0.2772, 0.2279, 0.2505, 0.2444],
          [0.2673, 0.2322, 0.2538, 0.2467],
          [0.2604,

In [7]:
output = torch.tensor([[[[0.4741, 0.4795, 0.4852, 0.4799],
          [0.4767, 0.4818, 0.4878, 0.4824],
          [0.4564, 0.4468, 0.4523, 0.4432],
          [0.4691, 0.4691, 0.4759, 0.4696]],

         [[0.5259, 0.5205, 0.5148, 0.5201],
          [0.5233, 0.5182, 0.5122, 0.5176],
          [0.5436, 0.5532, 0.5477, 0.5568],
          [0.5309, 0.5309, 0.5241, 0.5304]]],


        [[[0.4822, 0.4636, 0.4619, 0.4845],
          [0.4435, 0.4266, 0.4161, 0.4501],
          [0.4583, 0.4464, 0.4364, 0.4637],
          [0.4601, 0.4355, 0.4302, 0.4856]],

         [[0.5178, 0.5364, 0.5381, 0.5155],
          [0.5565, 0.5734, 0.5839, 0.5499],
          [0.5417, 0.5536, 0.5636, 0.5363],
          [0.5399, 0.5645, 0.5698, 0.5144]]],


        [[[0.4031, 0.4354, 0.4224, 0.4244],
          [0.3934, 0.4533, 0.4135, 0.4223],
          [0.4526, 0.4638, 0.4443, 0.4508],
          [0.4177, 0.4542, 0.4355, 0.4369]],

         [[0.5969, 0.5646, 0.5776, 0.5756],
          [0.6066, 0.5467, 0.5865, 0.5777],
          [0.5474, 0.5362, 0.5557, 0.5492],
          [0.5823, 0.5458, 0.5645, 0.5631]]],


        [[[0.4468, 0.4277, 0.4373, 0.4173],
          [0.4691, 0.4594, 0.4622, 0.4563],
          [0.4602, 0.4441, 0.4515, 0.4375],
          [0.4539, 0.4398, 0.4455, 0.4322]],

         [[0.5532, 0.5723, 0.5627, 0.5827],
          [0.5309, 0.5406, 0.5378, 0.5437],
          [0.5398, 0.5559, 0.5485, 0.5625],
          [0.5461, 0.5602, 0.5545, 0.5678]]],


        [[[0.4725, 0.4685, 0.4824, 0.4545],
          [0.4388, 0.4321, 0.4542, 0.4318],
          [0.4573, 0.4544, 0.4660, 0.4222],
          [0.4519, 0.4390, 0.4492, 0.4228]],

         [[0.5275, 0.5315, 0.5176, 0.5455],
          [0.5612, 0.5679, 0.5458, 0.5682],
          [0.5427, 0.5456, 0.5340, 0.5778],
          [0.5481, 0.5610, 0.5508, 0.5772]]],


        [[[0.4403, 0.4518, 0.4612, 0.4549],
          [0.4550, 0.4628, 0.4800, 0.4645],
          [0.4616, 0.4691, 0.4900, 0.4745],
          [0.4201, 0.4379, 0.4539, 0.4426]],

         [[0.5597, 0.5482, 0.5388, 0.5451],
          [0.5450, 0.5372, 0.5200, 0.5355],
          [0.5384, 0.5309, 0.5100, 0.5255],
          [0.5799, 0.5621, 0.5461, 0.5574]]],


        [[[0.4268, 0.4249, 0.4533, 0.4345],
          [0.4436, 0.4483, 0.4612, 0.4488],
          [0.4354, 0.4414, 0.4563, 0.4451],
          [0.4521, 0.4374, 0.4762, 0.4543]],

         [[0.5732, 0.5751, 0.5467, 0.5655],
          [0.5564, 0.5517, 0.5388, 0.5512],
          [0.5646, 0.5586, 0.5437, 0.5549],
          [0.5479, 0.5626, 0.5238, 0.5457]]],


        [[[0.4699, 0.4451, 0.4572, 0.4596],
          [0.4687, 0.4464, 0.4600, 0.4602],
          [0.4973, 0.4804, 0.4864, 0.4878],
          [0.4446, 0.4202, 0.4391, 0.4339]],

         [[0.5301, 0.5549, 0.5428, 0.5404],
          [0.5313, 0.5536, 0.5400, 0.5398],
          [0.5027, 0.5196, 0.5136, 0.5122],
          [0.5554, 0.5798, 0.5609, 0.5661]]],


        [[[0.4567, 0.4357, 0.4384, 0.4264],
          [0.4305, 0.4014, 0.4075, 0.3789],
          [0.4502, 0.4313, 0.4443, 0.4357],
          [0.4326, 0.4100, 0.4212, 0.3989]],

         [[0.5433, 0.5643, 0.5616, 0.5736],
          [0.5695, 0.5986, 0.5925, 0.6211],
          [0.5498, 0.5687, 0.5557, 0.5643],
          [0.5674, 0.5900, 0.5788, 0.6011]]],


        [[[0.4318, 0.4433, 0.4363, 0.4227],
          [0.4588, 0.4654, 0.4709, 0.4492],
          [0.4256, 0.4398, 0.4407, 0.4167],
          [0.4201, 0.4355, 0.4238, 0.4113]],

         [[0.5682, 0.5567, 0.5637, 0.5773],
          [0.5412, 0.5346, 0.5291, 0.5508],
          [0.5744, 0.5602, 0.5593, 0.5833],
          [0.5799, 0.5645, 0.5762, 0.5887]]]])

In [4]:
encoder(rands).size()

          [ 9.7510e-03,  1.2439e-02,  3.5460e-02,  1.4968e-02],
          [ 3.1569e-02,  7.9339e-03, -2.2924e-03,  1.1331e-03],
          [ 2.3694e-02,  2.3631e-02,  3.9638e-02,  2.2374e-02]],

         [[ 1.2537e-01,  1.0683e-01,  1.0554e-01,  1.0506e-01],
          [ 1.0300e-01,  8.5335e-02,  8.4349e-02,  8.5436e-02],
          [ 2.0658e-01,  2.2153e-01,  1.8907e-01,  2.2919e-01],
          [ 1.4749e-01,  1.4746e-01,  1.3614e-01,  1.4399e-01]]],


        [[[ 1.6531e-02,  4.6004e-02,  1.4361e-02,  2.1016e-02],
          [ 3.1137e-02,  5.6010e-02,  3.7463e-02, -7.4020e-03],
          [ 4.5790e-02,  8.2320e-02,  6.0429e-02, -1.2206e-03],
          [-4.7968e-02, -5.9232e-02, -8.9583e-02,  1.1392e-02]],

         [[ 8.7872e-02,  1.9167e-01,  1.6725e-01,  8.3198e-02],
          [ 2.5791e-01,  3.5175e-01,  3.7615e-01,  1.9301e-01],
          [ 2.1294e-01,  2.9759e-01,  3.1604e-01,  1.4411e-01],
          [ 1.1194e-01,  2.0009e-01,  1.9151e-01,  6.9000e-02]]],


        [[[ 2.8831e-02, -3.4

torch.Size([10, 4, 6])

In [27]:
torch.masked_fill(mask=mask, value=0)

TypeError: masked_fill() received an invalid combination of arguments - got (mask=Tensor, value=int, ), but expected one of:
 * (Tensor input, Tensor mask, Tensor value)
 * (Tensor input, Tensor mask, Number value)


In [25]:
mask = torch.tril(torch.ones(4,4), diagonal=0).bool()

In [12]:
pad_id = 0
vocab_size = 100
max_len = 10
hidden_dim = 6

def padding(data: list, pad_id: int=0) -> (list, int):
    max_len = len(max(data, key=len))
    output = [sample + [pad_id]*(max_len-len(sample)) for sample in tqdm(data)]
    return output, max_len

data = [
     [62, 13, 47, 39, 78, 33, 56, 13, 39, 29],
     [60, 96, 51, 32, 90, 44, 86, 71, 36, 18],
     [35, 45, 48, 65, 91, 99, 92, 10, 31, 21],
     [75, 51, 45, 48, 65, 91, 99, 11, 13, 28],
     [66, 88, 98, 47, 48, 65, 17, 13, 67, 99],
     ]

# data, max_len = padding(data)
data = torch.LongTensor(data)
print(data.shape)

torch.Size([5, 10])


In [13]:
embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=hidden_dim)
embedding.weight.data.uniform_(-1, 1)
print('Weight initialized')

Weight initialized


In [14]:
X_embedded = embedding(data)
X_embedded.size()

torch.Size([5, 10, 6])

In [15]:
w_query = nn.Linear(in_features=hidden_dim, out_features=hidden_dim) # Query
w_key = nn.Linear(in_features=hidden_dim, out_features=hidden_dim) # Key
w_value = nn.Linear(in_features=hidden_dim, out_features=hidden_dim) # Value

query = w_query(X_embedded)
key = w_key(X_embedded)
value = w_value(X_embedded)

In [19]:
attention = MultiHeadAttention(hidden_dim=hidden_dim, num_heads=2)
attention_mat = attention(query, key, value)

In [21]:
attention_mat.size()

torch.Size([5, 10, 6])

In [26]:
attn_layer_norm = nn.LayerNorm(normalized_shape=(10, 6))

In [25]:
attention_mat.size()[1:]

torch.Size([10, 6])

In [27]:
attn_layer_norm(attention_mat).size()

torch.Size([5, 10, 6])