In [1]:
import torch

In [19]:
x = torch.randn(1, requires_grad=True)
y = x*3
y

tensor([-0.3643], grad_fn=<MulBackward0>)

In [33]:
x = torch.randn(2, requires_grad=True)
y = 3*x
z = x/2
w = x + y
u = (x + y / z) ** w
j = x + y - z
k = x - y * w * j

In [34]:
# 마지막 연산을 기준으로 attribute가 결정됨
print(y)
print(z)
print(w)
print(u)
print(j)

tensor([-1.8743, -2.7506], grad_fn=<MulBackward0>)
tensor([-0.3124, -0.4584], grad_fn=<DivBackward0>)
tensor([-2.4991, -3.6675], grad_fn=<AddBackward0>)
tensor([0.0150, 0.0026], grad_fn=<PowBackward1>)
tensor([-2.1867, -3.2091], grad_fn=<SubBackward0>)


In [13]:
x = torch.randn(2, requires_grad=True)

def get_y(x):
    return x*3

In [14]:
loss = get_y(x)

In [15]:
loss.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [11]:
z = torch.rand(3, requires_grad=True)

In [8]:
gradients = torch.tensor([100, .1], dtype=torch.float)
y.backward(gradients)
x.grad


tensor([300.0000,   0.3000])

In [9]:
y.grad

ipykernel_launcher:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
