In [6]:
from tqdm import tqdm

import torch
from torch import nn
from torch.nn import functional as F

In [15]:
pad_id = 0
vocab_size = 100
max_len = 10
hidden_dim = 6

def padding(data: list, pad_id: int=0) -> (list, int):
    max_len = len(max(data, key=len))
    output = [sample + [pad_id]*(max_len-len(sample)) for sample in tqdm(data)]
    return output, max_len

data = [
     [62, 13, 47, 39, 78, 33, 56, 13, 39, 29],
     [60, 96, 51, 32, 90, 44, 86, 71, 36, 18],
     [35, 45, 48, 65, 91, 99, 92, 10, 31, 21],
     [75, 51, 45, 48, 65, 91, 99, 11, 13, 28],
     [66, 88, 98, 47, 48, 65, 17, 13, 67, 13],
     ]

# data, max_len = padding(data)
data = torch.LongTensor(data)
print(data.shape)

torch.Size([5, 10])


In [16]:
embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=hidden_dim)

w_query = nn.Linear(in_features=hidden_dim, out_features=hidden_dim)
w_key = nn.Linear(in_features=hidden_dim, out_features=hidden_dim)
w_value = nn.Linear(in_features=hidden_dim, out_features=hidden_dim)

embedding.weight.data.uniform_(-1, 1)
w_query.weight.data.uniform_(-1, 1)
w_key.weight.data.uniform_(-1, 1)
w_value.weight.data.uniform_(-1, 1)
print('Initialized')

Initialized


In [19]:
embedding(data).shape # (batgch_size, seq_length, max_length, embedding_dim)

torch.Size([5, 10, 6])

In [20]:
torch.zeros(1,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [18]:
w_query(output_embedding).shape #  (batch_size, seq_len, max_len, hidden_dim)

NameError: name 'output_embedding' is not defined

In [25]:
batch_size = 1
max_len = 4
num_heads = 2
d_k = 3
q = torch.ones(batch_size, max_len, num_heads, d_k)
k = torch.ones(batch_size, max_len, num_heads, d_k)
q, k

(tensor([[[[1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.]]]]),
 tensor([[[[1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.]]]]))

In [27]:
k.transpose(-2, -1)

tensor([[[[1., 1.],
          [1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.],
          [1., 1.]]]])

In [63]:
temp = torch.LongTensor(
        [
        [[[  1,   1]],
        [[  1,   1]]],
        [[[ 10,  10]],
        [[  1,   1]]],
        [[[100, 100]],
        [[  1,   1]]]
        ])

temp2 = torch.LongTensor(
    [[[1],
         [1]],

        [[2],
         [2]],

        [[3],
         [3]],

        [[4],
         [4]]])

In [64]:
temp.size(), temp2.size()

(torch.Size([3, 1, 1, 2]), torch.Size([4, 2, 1]))

In [71]:
a1 = [[1, 2], [3, 4], [5,6]]
a2 = [[10, 20], [30, 40], [50,60]]

temp = torch.LongTensor([a1, a2])

In [76]:
temp.transpose(1,2)

tensor([[[ 1,  3,  5],
         [ 2,  4,  6]],

        [[10, 30, 50],
         [20, 40, 60]]])